export const AUTH_TYPES = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_LOADED: "LOGIN_LOADED",
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGOUT_USER: "LOGOUT_USER",
  GET_USER_WITH_TOKEN: "GET_USER_WITH_TOKEN",
  GET_USERS: "GET_USERS",
  AUTH_ERROR: "AUTH_ERROR",
  LOGIN_FAILED: "LOGIN_FAILED",
};
